# Generated by Django 3.2.7 on 2021-09-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verona', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('msg', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
