# Generated by Django 3.2.7 on 2021-09-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verona', '0004_rename_feedback_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.FileField(blank=True, upload_to='featured-projects/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects/%Y/%m/%d/'),
        ),
    ]
