# Generated by Django 3.2.7 on 2021-09-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verona', '0005_auto_20210904_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.RemoveField(
            model_name='featuredproject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='featuredproject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='featuredproject',
            name='image',
        ),
        migrations.RemoveField(
            model_name='featuredproject',
            name='name',
        ),
        migrations.RemoveField(
            model_name='featuredproject',
            name='updated_at',
        ),
    ]
