# Generated by Django 3.2.7 on 2021-09-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verona', '0006_auto_20210904_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments')),
            ],
        ),
        migrations.DeleteModel(
            name='FeaturedProject',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
