# Generated by Django 3.2.7 on 2021-09-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verona', '0008_auto_20210904_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='Project', max_length=64),
        ),
    ]
