# Generated by Django 3.2.7 on 2021-09-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verona', '0013_rename_file_project_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='text'),
        ),
    ]
