# Generated by Django 3.2.7 on 2021-09-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verona', '0014_project_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedProject',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='project',
            name='main_photo',
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
