# Generated by Django 3.2.7 on 2021-09-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verona', '0015_auto_20210904_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='main_photo',
        ),
    ]
