# Generated by Django 3.2.7 on 2021-09-04 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verona', '0016_rename_image_project_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_photo',
            field=models.ImageField(blank=True, upload_to='main_pics/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verona.project')),
            ],
        ),
    ]
