# Generated by Django 3.2.7 on 2021-09-06 20:57

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('verona', '0018_project_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[400, 420], upload_to='main_pics/%Y/%m/%d/'),
        ),
    ]
