# Generated by Django 3.2.7 on 2021-09-06 21:20

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('verona', '0025_alter_project_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=50, size=[500, 500], upload_to='main_pics/%Y/%m/%d/'),
        ),
    ]
