# Generated by Django 3.2.7 on 2021-09-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verona', '0027_alter_project_main_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
